# Generated by Django 5.2.4 on 2025-09-24 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
