# Generated by Django 5.2.4 on 2025-11-05 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
