# Generated by Django 5.2.4 on 2025-12-24 06:49

import cloudinary_storage.storage
import learning_logs.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='entry_files/', validators=[learning_logs.utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='entry_images/', validators=[learning_logs.utils.validators.validate_image_size]),
        ),
    ]
