# Generated by Django 5.2.4 on 2025-12-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_alter_files_file_alter_images_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Complaint text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_comments', to='learning_logs.comment', verbose_name='Comment')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_complaints_received', to=settings.AUTH_USER_MODEL, verbose_name='Offender')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_complaints_made', to=settings.AUTH_USER_MODEL, verbose_name='The author of the complaint comment')),
            ],
            options={
                'unique_together': {('owner', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='ComplaintTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Complaint text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_complaints_received', to=settings.AUTH_USER_MODEL, verbose_name='Offender')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_complaints_made', to=settings.AUTH_USER_MODEL, verbose_name='The author of the complaint topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_topics', to='learning_logs.topic', verbose_name='Topic')),
            ],
            options={
                'unique_together': {('owner', 'topic')},
            },
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
